# Generated by Django 3.2.9 on 2021-11-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='summ',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
