# Generated by Django 3.2.9 on 2021-11-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_departments_summ'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='output',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
