# Generated by Django 3.2.9 on 2021-11-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_departments_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='output',
            field=models.CharField(default='null', max_length=100000),
        ),
        migrations.AlterField(
            model_name='departments',
            name='summ',
            field=models.CharField(default='null', max_length=100000),
        ),
    ]
