# Generated by Django 3.2.9 on 2022-01-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_auto_20211129_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='AudioFileName',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
