# Generated by Django 3.2.9 on 2022-01-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_employees_audiofilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Department',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='EmployeeName',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='PhotoFileName',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
