# Generated by Django 3.2.9 on 2022-01-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0006_auto_20220105_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='AudioSummary',
            field=models.CharField(default='null', max_length=1000000),
        ),
        migrations.AddField(
            model_name='employees',
            name='AudioText',
            field=models.CharField(default='null', max_length=1000000),
        ),
    ]
